import { Shape } from './types';

export const SHAPES: Shape[] = [
  // New 2D Shapes
  {
    name: 'Oval',
    type: '2D',
    description: 'An oval is like a stretched circle, similar to the shape of an egg.',
    properties: { Sides: '0 (1 curved edge)', Vertices: 0 },
    color: '#fb7185',
    colorName: 'rose',
  },
  {
    name: 'Rhombus',
    type: '2D',
    description: 'A rhombus is a four-sided shape where all sides have equal length. It looks like a tilted square or a diamond.',
    properties: { Sides: 4, Vertices: 4, 'Side Lengths': 'Equal' },
    color: '#38bdf8',
    colorName: 'sky',
  },
  {
    name: 'Heart',
    type: '2D',
    description: 'A heart shape is a symbol of love! It has a pointed bottom and two rounded lobes at the top.',
    properties: { Sides: '0 (1 curved edge)', Points: 1 },
    color: '#ef4444',
    colorName: 'red',
  },
  // 2D Shapes
  {
    name: 'Circle',
    type: '2D',
    description: 'A circle is a round shape where all points on the edge are the same distance from the center.',
    properties: { Sides: '0 (1 curved edge)', Vertices: 0 },
    color: '#60a5fa',
    colorName: 'blue',
  },
  {
    name: 'Square',
    type: '2D',
    description: 'A square has four equal straight sides and four right (90-degree) angles.',
    properties: { Sides: 4, Vertices: 4, 'Side Lengths': 'Equal' },
    color: '#facc15',
    colorName: 'yellow',
  },
  {
    name: 'Rectangle',
    type: '2D',
    description: 'A rectangle is a shape with four straight sides and four right angles. Opposite sides are equal in length.',
    properties: { Sides: 4, Vertices: 4, 'Opposite Sides': 'Equal' },
    color: '#4ade80',
    colorName: 'green',
  },
  {
    name: 'Triangle',
    type: '2D',
    description: 'A triangle is a shape with three straight sides and three angles.',
    properties: { Sides: 3, Vertices: 3 },
    color: '#f87171',
    colorName: 'red',
  },
  {
    name: 'Star',
    type: '2D',
    description: 'A star is a shape that often has five or more points, like the ones you see in the night sky!',
    properties: { Points: 5, Sides: 10, Vertices: 10 },
    color: '#fbbf24',
    colorName: 'amber',
  },
  {
    name: 'Pentagon',
    type: '2D',
    description: 'A pentagon is a shape with five straight sides and five angles.',
    properties: { Sides: 5, Vertices: 5 },
    color: '#a78bfa',
    colorName: 'violet',
  },
  {
    name: 'Hexagon',
    type: '2D',
    description: 'A hexagon is a shape with six straight sides and six angles, like a honeycomb cell!',
    properties: { Sides: 6, Vertices: 6 },
    color: '#22d3ee',
    colorName: 'cyan',
  },
  // New 3D Shapes
  {
    name: 'Cuboid',
    type: '3D',
    description: 'A cuboid, or rectangular prism, is a 3D shape like a box. It has six rectangular faces.',
    properties: { Faces: 6, Edges: 12, Vertices: 8 },
    color: '#a855f7',
    colorName: 'purple',
  },
  {
    name: 'Torus',
    type: '3D',
    description: 'A torus is a 3D shape that looks like a donut or a ring. It has no corners or edges.',
    properties: { Faces: 0, Edges: 0, Vertices: 0 },
    color: '#d946ef',
    colorName: 'fuchsia',
  },
  // 3D Shapes
  {
    name: 'Cube',
    type: '3D',
    description: 'A cube is a 3D shape with six square faces, twelve edges, and eight corners. All sides are equal.',
    properties: { Faces: 6, Edges: 12, Vertices: 8 },
    color: '#f472b6',
    colorName: 'pink',
  },
  {
    name: 'Sphere',
    type: '3D',
    description: 'A sphere is a perfectly round 3D object, like a ball. It has no faces, edges, or corners.',
    properties: { Faces: 0, Edges: 0, Vertices: 0 },
    color: '#34d399',
    colorName: 'emerald',
  },
  {
    name: 'Cylinder',
    type: '3D',
    description: 'A cylinder has two flat circular ends and one curved side, like a can of soup.',
    properties: { 'Flat Faces': 2, 'Curved Surfaces': 1, Edges: 2 },
    color: '#f97316',
    colorName: 'orange',
  },
  {
    name: 'Cone',
    type: '3D',
    description: 'A cone has a flat circular base and a pointed top called the apex, like an ice cream cone!',
    properties: { 'Flat Face': 1, 'Curved Surface': 1, Vertex: 1, Edge: 1 },
    color: '#818cf8',
    colorName: 'indigo',
  },
  {
    name: 'Pyramid',
    type: '3D',
    description: 'A pyramid has a flat base (often a square) and triangular sides that meet at a point at the top.',
    properties: { Faces: 5, Edges: 8, Vertices: 5 },
    color: '#eab308',
    colorName: 'yellow',
  },
  // 4D Shapes
  {
    name: 'Tesseract',
    type: '4D',
    description: 'A tesseract is a four-dimensional cube! We see its shadow in 3D, like a small cube floating inside a bigger cube.',
    properties: { '3D "Faces" (Cells)': 8, Faces: 24, Edges: 32, Vertices: 16 },
    color: '#14b8a6',
    colorName: 'teal',
  },
];